[package]
name = "rusty_notes"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.27.0"
ratatui = "0.27.0"
rusqlite = { version = "0.32.1", features = ["bundled", "chrono"] }
